spring:
  application:
    name: ad-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    # 单节点的 eureka-server, 不需要同步其他节点的 eureka-server,
    fetch-registry: false #  默认为 true
    register-with-eureka: false # 不将自己注册到 eureka-server, 默认为true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/