spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runoob?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: nroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

    hibernate:
      #      是否自动建库。默认为none , Hibernate 能根据Entity 类      的定义自动生成表以及修改己有的表和表主外键设置等。可选值: none, update
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8085